apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: contacts
  annotations:
    configsync.gke.io/cluster-name-selector: cymbal-prod
spec:
  hard:
    cpu: 700m
    memory: 512Mi